### ISSUE TITLE
the new dashboad.php is  showing just dark background 

### ISSUE THREAD

**Issue by anonymouss234** [4xx404/CookieCatch#12]
the new  dashboard.php is not displaying results interface, it showing just dark background here is the screenshot of what im saying https://prnt.sc/COrAoqwg3sY1   pls kindly fix brother

**Comment by 4xx404** [comment]
@anonymouss234 I don't see just a dark background?
![dashboard-cookie-catch](https://user-images.githubusercontent.com/45526353/209405209-f8f8bfa1-47eb-4431-95b7-b63ab5658744.png)

**Comment by 4xx404** [comment]
@anonymouss234 this is related to the other issue you've opened & I believe you are using an old version of PHP that doesn't allow type hinting, which isn't an issue with the tool.

**Comment by anonymouss234** [comment]
Maybe  made a mistake with the script you uploaded on here cuz this was the error issue I got from the error log and it showing just dark background from dashboard.php

PHP Parse error:  syntax error, unexpected '|', expecting variable (T_VARIABLE) in /home3/lanceli1/public_html/co2/Core/Classes/HTMLBuilder.php on line 230

**Comment by 4xx404** [comment]
@anonymouss234 yeah that's the cause from the 2nd issue you've just raised. Fix applied there

**Comment by anonymouss234** [comment]
After I applied the new code you fixed. The dashboard works perfectly and it shows results but the index.php is not redirecting, it shows just white blank. And this is the error log 


Cannot modify header information - headers already sent by (output started at /home3/lanceli1/public_html/co2/Core/Classes/Config.php:1) in /home3/lanceli1/public_html/co2/Core/Classes/Redirect.php on line 15
