### ISSUE TITLE
the error is on HTMLBuilder.php file 

### ISSUE THREAD

**Issue by anonymouss234** [4xx404/CookieCatch#13]
Here is the error PHP Parse error:  syntax error, unexpected '|', expecting variable (T_VARIABLE) in /home3/lanceli1/public_html/co2/Core/Classes/HTMLBuilder.php on line 230

**Comment by 4xx404** [comment]
@anonymouss234 what device & version of PHP are you using? This works fine on my machine

**Comment by anonymouss234** [comment]
I am using php 7.4.33 and php 7.1.33

**Comment by anonymouss234** [comment]
On a cpanel platform

**Comment by 4xx404** [comment]
@anonymouss234 non-breaking change to fix this for earlier versions of PHP [PR](https://github.com/4xx404/CookieCatch/pull/14)
