### ISSUE TITLE
chmod 777 catch.php

### ISSUE THREAD

**Issue by YasirAsim** [4xx404/CookieCatch#2]
I'm using window 10 and unable to execute this command "chmod 777 catch.php"
is there any alternative way to use chmod 777 in window 10?

**Comment by 4xx404** [comment]
This should help you

icacls notepad.exe /grant Everyone:F

**Comment by 4xx404** [comment]
There's no chmod command in Windows. Either use Explorer's properties page for the file or from a command shell, use the attrib or cacls commands. Installing Cygwin provides a chmod command utility.

**Comment by 4xx404** [comment]
I dont usually work on windows machines but from what I have found, this should help

Roughly:
icacls notepad.exe /grant Everyone:F

Let me know if this helps so I can close the issue.

**Comment by 4xx404** [comment]
Whichever location that you cloned to, catch.php will be inside. cd into
CookieCatch directory & try again.

**Comment by 4xx404** [comment]
ahh changed file structure, need to change readme, completely went over my head haha use the index.php instead of catch.php(old file)

**Comment by 4xx404** [comment]
ahh changed file structure, need to change readme, completely went over my head haha use the index.php instead of catch.php(old file). Updated now, check the instructions again.
