### ISSUE TITLE
Can't access the dashboard

### ISSUE THREAD

**Issue by ghost** [4xx404/CookieCatch#4]
Hello,
my problem is that i can't access the dashboard.
can somebody tell me how i can do that.

Everytime i try to access the dashboard it redirects me to Google.
The console says:
[Thu Apr 21 18:49:03 2022] MY-IP:53573 Accepted
[Thu Apr 21 18:49:03 2022] MY-IP:53573 [302]: GET /dashboard.php
[Thu Apr 21 18:49:03 2022] MY-IP:53573 Closing

**Comment by 4xx404** [comment]
![cookie-catch-dashboard-redirect-blur](https://user-images.githubusercontent.com/45526353/164519384-71b19110-5021-4443-8ff5-7a21c86f8215.png)

 @leJsf there is no issue here, look at the attachment & notice the URL.
 
 The index.php file is what will redirect to Google & the file which is to be sent to the target; all the work is done before the Redirect.
 
 The dashboard.php (shown in the image), is what you would use to view the results. There is no redirect to google within this script which indicates that you are accessing the wrong URL. 
 
TIP: Alternatively, you can start your local PHP server & click the "here" link to open the dashboard directly from this repo's readme file

**Comment by ghost** [comment]
Ok, i completely deleted the index.php now and it works fine for me now

**Comment by 4xx404** [comment]
> Ok, i completely deleted the index.php now and it works fine for me now

It can't possibly work fine, index.php is the main script used for collecting the data which is then fed through to dashboard.php. No index.php means no data to display on the dashboard, like ever. What you need to do instead is set the port as 8000 in your server command rather than 80.
