### ISSUE TITLE
Error on line 84 on client.php script 

### ISSUE THREAD

**Issue by anonymouss234** [4xx404/CookieCatch#6]
#Thier is a syntax error when I tried to ruin code. there is an error on line 84 on client.php script. 

Parse error: syntax error, unexpected '|', expecting ';' or '{' in C:\xampp\htdocs\co\co\Core\Classes\Client.php on line 84.

Please kindly leave a comment with the correct code

**Comment by 4xx404** [comment]
@anonymouss234 This should be fixed now in this [PR](https://github.com/4xx404/CookieCatch/pull/7)
