### ISSUE TITLE
the result dashboard  interface 

### ISSUE THREAD

**Issue by anonymouss234** [4xx404/CookieCatch#8]
the viewing result dashboard interface is bad and it not showing more than one cookie result. please try and release a good dashboard result interface and that can show more than one result. here is the picture of what im talking about
![Screenshot_1](https://user-images.githubusercontent.com/121200359/209086748-9c662a2c-0860-4aac-a9de-3c29131be7e5.png)

**Comment by anonymouss234** [comment]
and can the tool grab user and pass of victim also?

**Comment by anonymouss234** [comment]
Can the tool grab user and passwords along worh cookies

**Comment by 4xx404** [comment]
@anonymouss234 this is the first time this has been brought to my attention & was obviously not the intended result nor was it displayed like this in testing. I'll apply a fix tonight

**Comment by 4xx404** [comment]
@anonymouss234 should be sorted now from this [PR](https://github.com/4xx404/CookieCatch/pull/9/).
